create table tb_appointment (
    date TIMESTAMP WITHOUT TIME ZONE,
    dentist_id bigint,
    id bigint generated by default as identity,
    patient_id bigint,
    schedule_id bigint,
    status enum ('CANCELLED','COMPLETED','SCHEDULED'),
    primary key (id)
)