    create table tb_user (
        id bigint generated by default as identity,
        email varchar(255) UNIQUE,
        name varchar(255),
        password varchar(255),
        phone varchar(255),
        primary key (id)
    )