create table tb_notification (
    id bigint generated by default as identity,
    sent_date TIMESTAMP WITHOUT TIME ZONE,
    user_id bigint,
    message TEXT,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES tb_user
)