create table tb_notification (
    id bigint generated by default as identity,
    sent_date TIMESTAMP WITHOUT TIME ZONE,
    user_id bigint,
    message TEXT,
    PRIMARY KEY (id),
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES tb_user ON DELETE CASCADE
)