create table tb_rating (
    score integer,
    date TIMESTAMP WITHOUT TIME ZONE,
    dentist_id bigint,
    id bigint generated by default as identity,
    patient_id bigint,
    comment varchar(255),
    primary key (id)
)