CREATE TYPE appointment_status AS ENUM ('CANCELED','COMPLETED','SCHEDULED');

create table tb_appointment (
    date TIMESTAMP WITHOUT TIME ZONE,
    description varchar(255),
    dentist_id bigint,
    id bigint generated by default as identity,
    patient_id bigint,
    status appointment_status NOT NULL DEFAULT 'SCHEDULED',
    primary key (id),
    CONSTRAINT fk_appointment_dentist FOREIGN KEY (dentist_id) REFERENCES tb_dentist,
    CONSTRAINT fk_appointment_patient FOREIGN KEY (patient_id) REFERENCES tb_patient
)