create table tb_schedule (
    dentist_id bigint,
    id bigint generated by default as identity,
    unavailable_time_slot TIMESTAMP WITHOUT TIME ZONE,
    primary key (id),
    CONSTRAINT fk_schedule_dentist FOREIGN KEY (dentist_id) REFERENCES tb_dentist
)